version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432
  app:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_PASS: mypassword
      HOST: 0.0.0.0
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db